// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";
import { getPrismaCliDatabaseUrl } from "./lib/db/urls";

// Prefer .env over inherited shell vars so CLI uses the linked Neon URLs.
dotenv.config({ override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getPrismaCliDatabaseUrl(),
  },
});
